CREATE TABLE HOTELS(
ID INT,
CONSTRAINT HOTELS_ID PRIMARY KEY (ID),
NAME NVARCHAR2(50),
COUNTRY NVARCHAR2(50),
CITY NVARCHAR2(50),
STREET NVARCHAR2(50)
);
CREATE SEQUENCE HOTEL_SQ MINVALUE 1 MAXVALUE 100 START WITH 1 INCREMENT BY 1 ;