CREATE TABLE ROOMS(
ID INT,
CONSTRAINT ROOMS_ID PRIMARY KEY (ID),
GUESTS_NUMBER INT,
PRICE NUMBER (8,2),
BREAKFAST NUMBER (1,0) DEFAULT 0,
PETS_ALLOWED NUMBER (1,0) DEFAULT 0,
DATE_AVAILABLE_FROM TIMESTAMP,
HOTEL INT,
CONSTRAINT H_FK FOREIGN KEY (HOTEL)
REFERENCES HOTELS(ID)
);
CREATE SEQUENCE ROOM_SQ MINVALUE 1 MAXVALUE 100 START WITH 1 INCREMENT BY 1 ;